services:
  huntme-api:
    build: .
    container_name: huntme-api
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - mysql
      - redis
    networks:
      - sheba-network

  nginx:
    image: nginx:alpine
    container_name: huntme-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - huntme-api
    networks:
      - sheba-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: huntme_org_job_portal
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sheba-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - sheba-network

networks:
  sheba-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
